# Generated by Django 4.2.6 on 2024-05-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0002_register_delete_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='confirmpassword',
            new_name='confirm_password',
        ),
    ]
