# Generated by Django 4.2.6 on 2024-05-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0003_rename_confirmpassword_register_confirm_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
    ]
