# Generated by Django 4.2.6 on 2024-05-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0005_menuitem_submenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='menu_item',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='SubMenu',
        ),
    ]
