# Generated by Django 4.2.6 on 2024-05-10 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0006_remove_submenu_menu_item_delete_menuitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuform',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('menu_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_menu', to='footwearapp.menuform')),
            ],
        ),
    ]
