# Generated by Django 4.2.6 on 2024-05-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0007_alter_menuform_id_submenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuform',
            name='badge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menuform',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
