# Generated by Django 4.2.6 on 2024-05-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0008_menuform_badge_menuform_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('badge', models.CharField(max_length=300)),
            ],
        ),
    ]
