# Generated by Django 4.2.6 on 2024-05-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0009_badgemenu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BadgeMenu',
        ),
    ]
