# Generated by Django 5.0.6 on 2024-07-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0011_badgemenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='About/')),
            ],
        ),
        migrations.RemoveField(
            model_name='menuform',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='menuform',
            name='icon',
        ),
    ]
