# Generated by Django 5.0.6 on 2024-07-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0012_about_remove_menuform_badge_remove_menuform_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='AddWishlist/')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.CharField(max_length=50)),
            ],
        ),
    ]
