# Generated by Django 5.0.6 on 2024-07-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0013_addwishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddWishlist',
            new_name='ShopMore',
        ),
    ]
