# Generated by Django 5.0.6 on 2024-07-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0014_rename_addwishlist_shopmore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='AddWishlist/')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
